// The quote board's list. Every quote is under 60 characters and its attribution under 20, so
// quote plus "- Name" always fits the board's 22 by 6 grid once wrapped (quote-board.test.tsx proves it).
export type Quote = { text: string; by: string };
export const QUOTES: Quote[] = [
  { text: 'Stay hungry, stay foolish.', by: 'Steve Jobs' },
  { text: 'Well begun is half done.', by: 'Aristotle' },
  { text: 'Simplicity is the ultimate sophistication.', by: 'Leonardo da Vinci' },
  { text: 'Whatever you are, be a good one.', by: 'Abraham Lincoln' },
  { text: 'The best way out is always through.', by: 'Robert Frost' },
  { text: 'Fortune favors the bold.', by: 'Virgil' },
  { text: 'Do or do not. There is no try.', by: 'Yoda' },
  { text: 'Talk is cheap. Show me the code.', by: 'Linus Torvalds' },
  { text: 'Premature optimization is the root of all evil.', by: 'Donald Knuth' },
  { text: 'Make it work, make it right, make it fast.', by: 'Kent Beck' },
  { text: 'It always seems impossible until it is done.', by: 'Nelson Mandela' },
  { text: 'Action is the foundational key to all success.', by: 'Pablo Picasso' },
  { text: 'The secret of getting ahead is getting started.', by: 'Mark Twain' },
  { text: 'Well done is better than well said.', by: 'Benjamin Franklin' },
  { text: 'We are what we repeatedly do.', by: 'Will Durant' },
  { text: 'Not all those who wander are lost.', by: 'J.R.R. Tolkien' },
  { text: 'Nothing will work unless you do.', by: 'Maya Angelou' },
  { text: 'Turn your wounds into wisdom.', by: 'Oprah Winfrey' },
  { text: 'Done is better than perfect.', by: 'Sheryl Sandberg' },
  { text: 'First, solve the problem. Then, write the code.', by: 'John Johnson' },
  { text: 'Simplicity is prerequisite for reliability.', by: 'Edsger Dijkstra' },
  { text: 'Deleted code is debugged code.', by: 'Jeff Sickel' },
  { text: 'The best way to predict the future is to invent it.', by: 'Alan Kay' },
  { text: 'Curiosity is the wick in the candle of learning.', by: 'William Arthur Ward' },
  { text: 'So many books, so little time.', by: 'Frank Zappa' },
  { text: 'The scariest moment is always just before you start.', by: 'Stephen King' },
  { text: 'Science is organized knowledge.', by: 'Herbert Spencer' },
  { text: 'Nature is pleased with simplicity.', by: 'Isaac Newton' },
  { text: 'What I cannot create, I do not understand.', by: 'Richard Feynman' },
  { text: 'The first principle is that you must not fool yourself.', by: 'Richard Feynman' },
  { text: 'No pressure, no diamonds.', by: 'Thomas Carlyle' },
  { text: 'Make each day your masterpiece.', by: 'John Wooden' },
  { text: 'Be quick, but do not hurry.', by: 'John Wooden' },
  { text: 'Champions keep playing until they get it right.', by: 'Billie Jean King' },
  { text: 'Everything you can imagine is real.', by: 'Pablo Picasso' },
  { text: 'I would rather die of passion than of boredom.', by: 'Vincent van Gogh' },
  { text: 'Learning never exhausts the mind.', by: 'Leonardo da Vinci' },
  { text: 'Time flies like an arrow; fruit flies like a banana.', by: 'Groucho Marx' },
  { text: 'I am not young enough to know everything.', by: 'Oscar Wilde' },
  { text: 'Be yourself; everyone else is already taken.', by: 'Oscar Wilde' },
  { text: 'Do what you can, with what you have, where you are.', by: 'Theodore Roosevelt' },
  { text: 'Comparison is the thief of joy.', by: 'Theodore Roosevelt' },
  { text: 'An investment in knowledge pays the best interest.', by: 'Benjamin Franklin' },
  { text: 'The expert in anything was once a beginner.', by: 'Helen Hayes' },
  { text: 'Do not count the days, make the days count.', by: 'Muhammad Ali' },
  { text: 'It is hard to beat a person who never gives up.', by: 'Babe Ruth' },
  { text: 'Just keep swimming.', by: 'Dory, Finding Nemo' },
  { text: 'To infinity and beyond!', by: 'Buzz Lightyear' },
  { text: 'It is dangerous to go alone! Take this.', by: 'The Legend of Zelda' },
  { text: 'The mitochondria is the powerhouse of the cell.', by: 'Philip Siekevitz' },
  { text: 'Houston, we have had a problem.', by: 'Jim Lovell' },
  { text: 'Wonder is the beginning of wisdom.', by: 'Socrates' },
  { text: 'Luck is what happens when preparation meets opportunity.', by: 'Seneca' },
  { text: 'Without music, life would be a mistake.', by: 'Friedrich Nietzsche' },
  { text: 'Whatever you do, do it well.', by: 'Walt Disney' },
  { text: 'Simplify, simplify.', by: 'Henry David Thoreau' },
  { text: 'Hofstadter\'s Law: it always takes longer than you expect.', by: 'Douglas Hofstadter' },
];
// The board reads one line per row, so the attribution goes on its own line.
export const quoteText = (quote: Quote) => `${quote.text}\n- ${quote.by}`;
export const pickQuote = (random: () => number = Math.random) => QUOTES[Math.min(QUOTES.length - 1, Math.floor(random() * QUOTES.length))];
