import test from 'node:test';
import assert from 'node:assert/strict';
import {graphFromWorkspace,buildIndex,searchGraph,validateGraph} from '../shared/graph.mjs';
import {validateWorkspace} from '../shared/validate.mjs';
const stamp='2026-09-12T18:00:00Z';
const doc=(id,name,content,kind='note')=>({id,name,content,kind,tags:['Research'],pinned:false,created:stamp,updated:stamp});
function fixture(){return{version:1,docs:[doc('a','Carbonyl mechanisms','Nucleophilic addition to carbonyl compounds.'),doc('b','Mechanism review','Inspect atom mapping and charge conservation.','skill'),doc('c','Travel notes','Train schedules and hotel bookings.')],goals:[],conversations:[],generations:[],activity:[],relations:[{id:'e',source:'doc:a',target:'doc:b',relation:'uses_skill',created:stamp}]};}
test('graph exports real typed relationships and deduplicated topic hubs',()=>{const graph=graphFromWorkspace(fixture());assert.equal(graph.nodes.filter(n=>n.kind==='topic').length,1);assert.equal(graph.edges.filter(e=>e.origin==='explicit').length,1);assert.equal(graph.edges.filter(e=>e.relation==='tagged').length,3);assert.equal(validateGraph(graph),graph);});
test('retrieval ranks exact subject first and follows an explicitly related skill',()=>{const result=searchGraph(buildIndex(graphFromWorkspace(fixture())),'carbonyl',{budget:800,limit:1});assert.equal(result.matches[0].id,'doc:a');assert.equal(result.matches[1].id,'doc:b');assert.ok(result.context.length<=800);assert.equal(result.relationships[0].relation,'uses_skill');});
test('empty or absent lexical matches return no invented context',()=>{for(const q of ['','the and','unfindabletoken'])assert.equal(searchGraph(buildIndex(graphFromWorkspace(fixture())),q).matches.length,0);});
test('workspace rejects dangling, duplicate, self, and mis-typed relationships',()=>{for(const tweak of [w=>w.relations[0].target='doc:missing',w=>w.relations[0].target='doc:a',w=>w.relations.push({...w.relations[0],id:'other'}),w=>w.relations[0].target='doc:c']){const w=fixture();tweak(w);assert.throws(()=>validateWorkspace(w),/Invalid workspace/);}});
test('generated image bytes are excluded from agent text export',()=>{const w=fixture();w.docs[0].data='data:image/png;base64,AA==';const raw=JSON.stringify(graphFromWorkspace(w));assert.ok(!raw.includes('data:image'));});
test('1000-node retrieval benchmark: bounded excerpt selection and deterministic top result',()=>{const w=fixture();for(let i=0;i<1000;i++)w.docs.push(doc('bench'+i,'Notebook '+i,'Common notes on a different topic. '.repeat(30)));const started=performance.now();const index=buildIndex(graphFromWorkspace(w));const built=performance.now()-started;const searchStart=performance.now();const result=searchGraph(index,'carbonyl mechanisms',{limit:4,budget:2000});const elapsed=performance.now()-searchStart;assert.equal(result.matches[0].id,'doc:a');assert.ok(result.context.length<=2000);console.log(JSON.stringify({benchmark:'1003 document synthetic fixture',indexMs:+built.toFixed(2),queryMs:+elapsed.toFixed(2),corpusChars:result.stats.corpusChars,contextChars:result.stats.contextChars}));});

