"""catalogue.py - rebuild MEMORIES.md, one line per memory, with NO model call.

The catalogue is DERIVED, never authored. Every line is rebuilt from the memory
files themselves, so it cannot disagree with them. remember.py calls rebuild()
after every save, in the same command, so there is no path that writes a memory
without its catalogue line.

  python catalogue.py            rebuild MEMORIES.md
  python catalogue.py --check    exit 1 if the file on disk is not what a rebuild
                                 would produce (use this to prove it never drifted)

Two stores are catalogued:
  memories/YYYY-MM.md   what remember.py saves, one block per memory
  ../OS/memory/*.md     the standing notes, one file each
"""
from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path

BRAIN_DIR = Path(__file__).resolve().parent
CATALOGUE = BRAIN_DIR / "MEMORIES.md"
BLOCK_RE = re.compile(r"^## \[(\d{4}-\d{2}-\d{2})\] (\w+) \| (.+)$")
MAX_DESC = 140


def one_sentence(text: str) -> str:
    """Opening sentences of a paragraph, up to MAX_DESC characters.

    One sentence alone is often too short to say what a note holds ("These are
    settled."), so keep taking sentences while there is room.
    """
    flat = " ".join(text.split())
    if not flat:
        return "(no description)"
    out = ""
    for part in re.split(r"(?<=[.!?])\s", flat):
        if out and len(out) + 1 + len(part) > MAX_DESC:
            break
        out = f"{out} {part}".strip()
    if len(out) > MAX_DESC:
        out = out[:MAX_DESC].rsplit(" ", 1)[0] + "..."
    return out


def saved_memories() -> list[tuple[str, str, str]]:
    """(name, link, description) for every block in memories/*.md, newest first."""
    out = []
    for path in sorted((BRAIN_DIR / "memories").glob("*.md"), reverse=True):
        heading, body = None, []
        for line in path.read_text(encoding="utf-8").splitlines() + ["## [0000-00-00] x | end"]:
            match = BLOCK_RE.match(line)
            if match:
                if heading:
                    out.append((heading, f"memories/{path.name}", one_sentence(" ".join(body))))
                date, kind, _title = match.groups()
                # The title is only the first nine words of the text, so it would
                # repeat the description. Name the line by date and kind instead.
                heading, body = f"{date} {kind}", []
            elif heading and not line.startswith("#"):
                body.append(line)
    return out


def standing_notes() -> list[tuple[str, str, str]]:
    """(name, link, description) for every file in ../OS/memory/, by name."""
    out = []
    for path in sorted((BRAIN_DIR.parent / "OS" / "memory").glob("*.md")):
        lines = path.read_text(encoding="utf-8").splitlines()
        title = next((l.lstrip("# ").strip() for l in lines if l.startswith("# ")), path.stem)
        # The first paragraph of real prose after the title. Skip the "**Kind:**"
        # metadata block, sub-headings, and table or list rows, any of which would
        # otherwise be quoted as the description.
        after_title = lines[lines.index(f"# {title}") + 1:] if f"# {title}" in lines else lines
        body: list[str] = []
        for para in re.split(r"\n\s*\n", "\n".join(after_title)):
            head = para.strip()
            if head and not head.startswith(("**Kind:**", "#", "|", "-", "*", ">")):
                body = [head]
                break
        out.append((title, f"../OS/memory/{path.name}", one_sentence(" ".join(body))))
    return out


def render() -> str:
    saved, notes = saved_memories(), standing_notes()
    lines = [
        "# Memories catalogue",
        "",
        "Generated by catalogue.py. Do not edit by hand: every line is rebuilt from the",
        "memory files themselves, so this file cannot disagree with them. remember.py",
        "rebuilds it on every save.",
        "",
        f"Rebuilt {time.strftime('%Y-%m-%d %H:%M')}. "
        f"{len(saved)} saved memories, {len(notes)} standing notes.",
        "",
        "## Saved memories",
        "",
        "One block each in `memories/YYYY-MM.md`, written by `remember.py`.",
        "",
    ]
    lines += [f"- [{name}]({link}) - {desc}" for name, link, desc in saved] or ["(none yet)"]
    lines += [
        "",
        "## Standing notes",
        "",
        "One file each in `OS/memory/`, written by hand.",
        "",
    ]
    lines += [f"- [{name}]({link}) - {desc}" for name, link, desc in notes] or ["(none yet)"]
    return "\n".join(lines) + "\n"


def rebuild() -> int:
    """Write MEMORIES.md. Returns the number of catalogued items."""
    text = render()
    CATALOGUE.write_text(text, encoding="utf-8", newline="\n")
    return sum(1 for line in text.splitlines() if line.startswith("- ["))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if MEMORIES.md is not what a rebuild would produce")
    a = ap.parse_args()

    if a.check:
        if not CATALOGUE.exists():
            print("CATALOGUE: MEMORIES.md is missing. Run: python catalogue.py", file=sys.stderr)
            return 1
        # The timestamp line changes every rebuild, so compare everything else.
        strip = lambda t: [l for l in t.splitlines() if not l.startswith("Rebuilt ")]
        if strip(CATALOGUE.read_text(encoding="utf-8")) != strip(render()):
            print("CATALOGUE: MEMORIES.md has drifted. Run: python catalogue.py", file=sys.stderr)
            return 1
        print("catalogue: MEMORIES.md matches the memory files")
        return 0

    count = rebuild()
    print(f"catalogue: {CATALOGUE.name} rebuilt, {count} memories")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
